config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/views/carts/_cart.html.erb
 <tr>
  <td class="cart_product">
    <%= image_tag(cart.product.image, size:Settings.size.cart) %>
  </td>
  <td class="cart_description">
    <p><%= cart.product.name %></p>
  </td>
  <td class="cart_quantity">
    <%= link_to t("add"), items_path(product_id: cart.product.id),
    class:"btn btn-success",method: :post ,remote:true %>
    <%= cart.quantity %>
    <%= link_to t("remove"), line_item_path(product_id: cart.product.id),
    class:"btn btn-success", method: :put ,remote:true %>
  </td>
  <td class="cart_total">
    <p class="cart_total_price"><%= cart.product.price %></p>
  </td>
   <td class="cart_total">
    <p class="cart_total_price"><%= cart.quantity * cart.product.price %></p>
  </td>
  <td>
  <% if cannot? [:destroy], cart %>
    <%= link_to deleteitem_path(id: cart.id), method: :delete, remote:true, class: "add-to-cart pull-left" do %>
      <i class="fa fa-trash-o" aria-hidden="true" ></i>
    <% end %>
  <% end %>
  </td>
</tr>