config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :line_items, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: Settings.product.price}
  validates :quanlity, presence: true, numericality: {greater_than_or_equal_to: Settings.product.quanlity}
  validates :information, presence: true, length: {maximum: Settings.product.information}
  scope :sort_by_product, ->{order "created_at DESC"}
  scope :sort_by_products, ->{order :name}
  scope :not_original, ->(id){where.not(id: id)}
  scope :find_category, ->(q){where category_id: q if q.present?}
  scope :search_by_name, ->(content){where(" name like ?", "%#{content}%") if content.present?}
  scope :search_price, ->(prices){where(price: prices) if prices.present?}
  scope :product_hot, ->{joins(:order_details)
    .where("MONTH(order_details.created_at) = ?", Date.today.month)
    .group("products.id").order("sum(order_details.quanlity) DESC")}

  def self.sum_product product
    votes = product.ratings.pluck :vote
    (votes.sum.to_f / votes.count).round Settings.round.get if product.ratings.present?
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :admin_user, only: :destroy
  before_action :load_product, only: %i(destroy edit update)
  before_action :check_if_has_line_item, only: :destroy
  load_and_authorize_resource

  def show; end

  def index
    @product = Product.find_category(params[:q])
    @products = Product.sort_by_products
    @categories = Category.sort_by_category
  end

  def new
    @product = Product.new
    @cate = Category.sort_by_category
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "admin.create"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @cate = Category.sort_by_category
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = t "admin.updatesuc"
    else
      flash[:warning] = t "admin.updatefail"
    end
    redirect_to admin_products_path
  end

  def destroy
    if @product.destroy
      flash[:success] = t "admin.deleted"
    else
      flash[:warning] = t "admin.notdelete"
    end
    redirect_to admin_products_path
  end

  private

  def check_if_has_line_item
    return if @product.order_details.empty?
    flash[:danger] = t "admin.notdelete"
    redirect_to admin_products_path
  end

  def product_params
    params.require(:product).permit(:name, :price, :quanlity, :image, :information, :category_id)
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_products_path
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :load_data, only: :show

  def show
    if @product
      @related_products = Product.not_original(params[:id]).sort_by_product.take(Settings.related_product.config)
      @new_products = Product.sort_by_product.take(Settings.new_product.config)
      recent_products.push @product
      recent_products
    else
      flash[:warning] = t "static_pages_controller.errors"
      redirect_to root_url
    end
  end

  private

  def load_data
    @product = Product.find_by id: params[:id]
    @ratings = Rating.show_ratings(params[:id]).order_vote
    @avg_rating = Product.sum_product @product
    @comments = Rating.show_comment(params[:id]).order_created
      .paginate(page: params[:page], per_page: Settings.comment.config)
  end
end

app/views/product/show.html.erb
  <div class="container">
    <div id="content">
      <div class="row">
        <div class="col-sm-9">
          <div class="row">
            <div class="col-sm-4">
              <%= image_tag(@product.image, size:Settings.size.img) %>
            </div>
            <div class="col-sm-8">
              <div class="single-item-body">
                <p class="single-item-title">
                  <%= t"product.show.name" %><%= @product.name %>
                </p>
                <p class="single-item-price">
                  <span><%= t"product.show.price" %><%= @product.price %><%=t"dollar"%></span>
                </p>
              </div>
              <div class="clearfix"></div>
              <div class="space20">&nbsp;</div>
              <div class="single-item-desc">
                <p><%= t"product.show.quanlity" %><%= @product.quanlity %></p>
              </div>
              <div class="space20">&nbsp;</div>
              <% if @product.quanlity > Settings.show.quanlity %>
                <p><%= t "product.show.addtocart" %></p>
                <div class="single-item-options">
                  <%= link_to line_items_path(product_id: @product.id), method: :post, class: "add-to-cart pull-left" do %>
                    <i class="fa fa-shopping-cart"></i>
                  <% end %>
                  <div class="clearfix"></div>
                </div>
              <% else %>
                <div class="alert alert-danger">
                  <%= t"product.show.status" %>
                </div>
              <%end %>
            </div>
          </div>
          <div class="space40">&nbsp;</div>
          <div class="woocommerce-tabs">
            <ul class="tabs">
              <li><a href="#tab-description"><%= t"product.show.description" %></a></li>
            </ul>
            <div class="panel" id="tab-description">
              <p><%= @product.information %></p>
            </div>
            <div class="panel" id="tab-reviews">
              <div class="row">
                <div class="col-md-5">
                    <%= form_tag ratings_path, method: :post, class: "formtest" do %>
                      <button type="button" class="btaval btn btn-success" data-toggle="collapse" data-target="#1" onClick="esconder(this)"><%= t"product.show.review" %></button>
                      <div id="1" class="collapse">
                        <div class="col-md-12 avaliar ">
                          <%= text_area_tag "comentario", t("comment"), cols: Settings.text.cols %>
                          <div class="stars starrr" data-rating="0">
                            <%= hidden_field_tag "rating", " ", class: "nota" %>
                          </div>
                            <div class="text-right">
                              <%= button_tag "Enviar",class: "btn btn-success" do %>
                                <i class="fa fa-reply"></i>
                              <% end %>
                              <span class="btn btn-danger " id = "bait" data-toggle="collapse" data-target="#1"><i class="fa fa-times"></i></span>
                              <%= hidden_field_tag "product_id", @product.id %>
                            </div>
                        </div>
                      </div>
                    <% end %>
                </div>
              </div>
              <div class="space20">&nbsp;</div>
              <% if @ratings.present? %>
                <h4><%= t"product.show.comment" %></h4>
                <%= render partial: "product", collection: @comments %>
                <%= will_paginate @comments %>
              <% end %>
              <div class="space20">&nbsp;</div>
              <% if @avg_rating.present? %>
               <div class="row">
                  <h4><%= t "product.show.avg"%></h4>
                  <h5>
                    <span><%= @avg_rating %></span>
                    <%= t "product.show.avgw"%>
                    <span class="glyphicon glyphicon-star"></span>
                  </h5>
                </div>
               <% end %>
              <div class="row">
                <div class="col-sm-5">
                  <% if @ratings.present? %>
                    <h4><%= t"product.show.rating" %></h4>
                    <% @ratings.each do |vote, products| %>
                      <div class="pull-left">
                        <div class="pull-left" style="width:35px; line-height:1;">
                          <div style="height:9px; margin:5px 0;"><%= vote %><span class="glyphicon glyphicon-star"></span></div>
                        </div>
                        <div class="pull-left" style="width:180px;">
                          <div class="progress" style="height:9px; margin:8px 0;">
                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5" style="width: 1000%">
                            </div>
                          </div>
                        </div>
                        <div class="pull-right" style="margin-left:10px;"><%=products.count %></div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="space50">&nbsp;</div>
          <div class="beta-products-list">
            <h4><%= t"product.show.related" %></h4>
            <div class="row">
             <% @related_products.each do |product| %>
                <div class="col-sm-4">
                  <div class="single-item">
                    <div class="ribbon-wrapper">
                      <div class="ribbon sale"><%= t"product.show.sale" %></div>
                    </div>
                    <div class="single-item-header">
                      <%= image_tag(product.image, size:Settings.size.img_product) %>
                    </div>
                    <div class="single-item-body">
                      <p class="single-item-title"><%= product.name %></p>
                      <p class="single-item-price">
                        <span class="flash-del"><%=t"dollar"%><%= product.price %></span>
                        <span class="flash-sale"><%=t"dollar"%><%= product.price %></span>
                      </p>
                    </div>
                    <div class="single-item-caption">
                      <%= link_to(product, class: "beta-btn primary") do %>
                        <%=t"static_pages.home.details"%>
                        <i class="fa fa-chevron-right"></i>
                      <% end %>
                      <div class="clearfix"></div>
                    </div>
                  </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-3 aside">
          <div class="widget">
            <h3 class="widget-title"><%=t"static_pages.home.newproduct"%></h3>
            <div class="widget-body">
              <div class="beta-sales beta-lists">
                <% @new_products.each do |newproduct| %>
                  <div class="media beta-sales-item">
                    <%= link_to(newproduct, class: "pull-left") do %>
                      <%= image_tag(newproduct.image) %>
                    <% end %>
                    <div class="media-body">
                      <h6><%= newproduct.name %></h6>
                      <span class="beta-sales-price"><%=t"dollar"%><%= newproduct.price %></span>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-3 aside">
          <div class="widget">
            <h3 class="widget-title"><%=t"product.show.recently"%></h3>
            <div class="widget-body">
              <div class="beta-sales beta-lists">
                <% recent_products.each do |newproduct| %>
                  <div class="media beta-sales-item">
                    <%= link_to(newproduct, class: "pull-left") do %>
                      <%= image_tag(newproduct.image) %>
                    <% end %>
                    <div class="media-body">
                      <h6><%= newproduct.name %></h6>
                      <span class="beta-sales-price"><%=t"dollar"%><%= newproduct.price %></span>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>