config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :admin_user, only: :destroy
  before_action :load_category, only: %i(edit destroy update)
  load_and_authorize_resource

  def index
    @categories = Category.sort_by_category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:info] = t "admin.create"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.updatesuc"
    else
      flash[:warning] = t "admin.updatefail"
    end
    redirect_to admin_categories_path
  end

  def destroy
    if @category.destroy
      flash[:success] = t "admin.deleted"
    else
      flash[:warning] = t "admin.notdelete"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:warning] = t "users_controller.errorss"
    redirect_to admin_categories_path
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/views/admin/categories/_category.html.erb
<% @categories .each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.created_at.to_date %></td>
    <td><%= category.updated_at.to_date  %></td>
    <td>
    <% if can? [:destroy, :update], category %>
      <%= link_to admin_category_path(category), method: :delete,
        class: "fa fa-trash-o btn btn-danger", data: {confirm: (t "users.index.sure") } do %>
      <% end %>
      <%= link_to edit_admin_category_path(category),
        class: "fa fa-pencil-square-o btn btn-danger" do %>
      <% end %>
    <% end %>
    </td>
  </tr>
<% end %>