config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "sessions/new"
  root "static_pages#index"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "category", to: "category#index"
  delete "/deleteitem", to: "line_items#destroy"
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders
    resources :orderdetails
    resources :suggests
    resources :statistics, only: :index
  end
  resources :suggests
  resources :static_pages
  resources :product
  resources :line_items
  resources :carts
  resources :items, only: [:create]
  resources :orders
  resources :users
  resources :ratings, only: [:create]
  resources :histories
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts._header.App"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts._header.home"), root_path %></li>
        <% if session[:cart_id].present? %>
          <li><%= link_to(cart_path(session[:cart_id])) do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
                <%= sum_quanlity  %>
                <%= t "layouts._header.item"%>
              <% end %>
          </li>
        <% end %>
        <% if user_signed_in?  %>
          <li><%= link_to t("layouts._header.suggest"), new_suggest_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to t("layouts._header.suggest"), admin_suggests_path %></li>
            <li><%= link_to t("layouts._header.category"), admin_categories_path %></li>
            <li><%= link_to t("layouts._header.product"), admin_products_path %></li>
            <li><%= link_to t("layouts._header.users"), admin_users_path %></li>
            <li><%= link_to t("layouts._header.order"), admin_orders_path  %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%= t("layouts._header.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts._header.profile"), user_path(current_user) %></li>
              <li><%= link_to t("layouts._header.history"), order_path(current_user) %></li>
              <li><%= link_to t("layouts._header.profile"), edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layouts._header.logout"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts._header.log"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>